const Prompts = {
  evaluation: (solution, result, solutionFormat, evaluationPrompt) => [
    'Evaluate the following solution for a problem:',
    '',
    'Expected solution:',
    solution,
    '',
    'Provided solution:',
    result,
    '',
    'The Format to compare is:',
    solutionFormat,
    '',
    'Evaluate the provided solution by comparing it with the expected solution.',
    'Assign a score between 0 and 10, where:',
    '- 10 means the solution is perfect',
    '- 0 means the solution is completely incorrect',
    'Provide a detailed evaluation in Markdown format.',
    '',
    'Respond ONLY with a JSON object in the following format:',
    '{',
    '  "score": [score between 0 and 10],',
    '  "evaluation": "[detailed evaluation in Markdown format]"',
    '}',
    ...(evaluationPrompt ? ['', evaluationPrompt] : []),
  ].join('\n'),

  personaAvatar: ({ name, description, personality }) => [
    "Create a realistic square profile photo of a person.",
    "Style: natural photorealistic headshot, professional but approachable, with realistic skin texture, facial features, hair, and clothing.",
    "Composition: centered head and upper shoulders, photographed straight-on from the front at eye level. The person must face the camera directly and look into the lens. Do not use a side profile, three-quarter angle, tilted pose, or cropped face.",
    "Use soft natural lighting and a simple realistic background with enough contrast around the subject.",
    "Vary the background between generations. Choose a subtle background that fits the person, such as a softly blurred office, library, cafe, home interior, outdoor setting, or a tasteful solid color. Vary the color palette and setting instead of always using the same neutral studio background.",
    "The result should look like a real profile photograph, not an illustration, cartoon, painting, 3D render, or stylized image.",
    "No text, logo, watermark, border, props, additional people, or distracting background elements.",
    "Output must be a single square image.",
    `Persona name: ${name || "Unknown"}.`,
    `Description: ${description || "No description provided"}.`,
    `Personality: ${personality || "No personality provided"}.`,
  ].join("\n"),

  problemAvatar: ({ name, description }) => [
    "Create a square cartoon icon for a problem or exercise.",
    "Style: clean flat vector-like illustration, thick black outlines, simple symbolic scene, plain muted solid background.",
    "Keep it very simple and readable at tiny sizes: use large clear shapes, very few details, high contrast, and one main visual idea.",
    "Composition: centered main object or situation, no text, no logo, no watermark, no photorealism.",
    "Output must be a single square image.",
    `Problem name: ${name || "Unknown"}.`,
    `Description: ${description || "No description provided"}.`,
  ].join("\n"),

  leiaAvatar: ({
    leiaName,
    personaName,
    personaDescription,
    problemDescription,
  }) => [
    "Create a square cartoon icon for a LEIA learning assistant configuration.",
    "Style: clean flat vector-like illustration, thick black outlines, simple symbolic scene, plain muted solid background.",
    "Keep it very simple and readable at tiny sizes: use large clear shapes, very few details, high contrast, and one main visual idea.",
    "Composition: centered main subject or situation, no text, no logo, no watermark, no photorealism.",
    "Output must be a single square image.",
    `LEIA name: ${leiaName || "Unknown"}.`,
    `Persona name: ${personaName || "Unknown"}.`,
    `Persona description: ${personaDescription || "No persona description provided"}.`,
    `Problem description: ${problemDescription || "No problem description provided"}.`,
  ].join("\n"),

  inphografic: (behaviour) => [
    "Create a polished A4 vertical infographic for the participant who will complete this specific LEIA exercise.",
    "The infographic must help the participant prepare and perform better during the interview, without revealing a complete answer or a scripted solution.",
    "",
    "Target format:",
    "- A4 vertical portrait layout.",
    "- Clear hierarchy, professional educational design, easy to scan in under one minute.",
    "- Use Spanish for all visible text.",
    "- Use short, actionable bullets. Avoid dense paragraphs.",
    "- Include small visual cues, icons, callouts, checklists, and a simple flow from preparation to interview execution.",
    "- Do not include logos, watermarks, fake UI controls, QR codes, or unreadable tiny text.",
    "",
    "Required content:",
    "- Title that clearly identifies this as a preparation guide for the exercise.",
    "- One concise summary of what the participant needs to achieve.",
    "- Key aspects to understand before starting the interview.",
    "- Practical advice for asking better questions in this exact scenario.",
    "- Recommended order for approaching the interview.",
    "- Common mistakes to avoid.",
    "- A small final checklist the participant can use during the exercise.",
    "",
    "Important boundaries:",
    "- Keep the guidance specific to the LEIA behaviour below.",
    "- Do not invent details that contradict the behaviour.",
    "- Do not provide the full solution, ideal final answer, or exact interview script.",
    "- The tone should be practical, direct, and encouraging, but not childish.",
    "",
    "LEIA behaviour:",
    behaviour,
  ].join("\n"),

  InphograficSolution: (behaviour) => [
    "Create a polished A4 vertical infographic for the teacher or evaluator of this specific LEIA exercise.",
    "The infographic must act as a solution-oriented guide: it should explain how a strong participant should conduct the interview and what evidence of good performance to look for.",
    "",
    "Target format:",
    "- A4 vertical portrait layout.",
    "- Professional educational design, structured for fast correction and classroom use.",
    "- Use Spanish for all visible text.",
    "- Use compact sections, scoring cues, flow arrows, checklists, and highlighted boxes for key evaluation points.",
    "- Avoid dense paragraphs. Prefer precise bullets and short rubrics.",
    "- Do not include logos, watermarks, fake UI controls, QR codes, or unreadable tiny text.",
    "",
    "Required content:",
    "- Title that clearly identifies this as the teacher solution guide.",
    "- Expected objective of the interview.",
    "- Recommended interview strategy, step by step.",
    "- The strongest questions the participant should ask and why they matter.",
    "- Key information the participant should uncover.",
    "- Signals of an excellent performance, an acceptable performance, and a weak performance.",
    "- Typical mistakes or omissions to detect.",
    "- A concise correction checklist or mini-rubric for the teacher.",
    "",
    "Important boundaries:",
    "- Make the content specific to the LEIA behaviour below.",
    "- Provide practical solution guidance, not generic interview advice.",
    "- Where the behaviour does not define an exact fact, state the expected reasoning instead of inventing hidden facts.",
    "- The tone should be precise, teacher-facing, and useful for evaluation.",
    "",
    "LEIA behaviour:",
    behaviour,
  ].join("\n"),

  
};

module.exports = Prompts;
