const Prompts = {
  evaluation: (solution, result, solutionFormat, evaluationPrompt) => [
    'Evaluate the following solution for a problem:',
    '',
    'Expected solution:',
    solution,
    '',
    'Provided solution:',
    result,
    '',
    'The Format to compare is:',
    solutionFormat,
    '',
    'Evaluate the provided solution by comparing it with the expected solution.',
    'Assign a score between 0 and 10, where:',
    '- 10 means the solution is perfect',
    '- 0 means the solution is completely incorrect',
    'Provide a detailed evaluation in Markdown format.',
    '',
    'Respond ONLY with a JSON object in the following format:',
    '{',
    '  "score": [score between 0 and 10],',
    '  "evaluation": "[detailed evaluation in Markdown format]"',
    '}',
    ...(evaluationPrompt ? ['', evaluationPrompt] : []),
  ].join('\n'),

  personaAvatar: ({ name, description, personality }) => [
    "Create a realistic square profile photo of a person.",
    "Style: natural photorealistic headshot, professional but approachable, with realistic skin texture, facial features, hair, and clothing.",
    "Composition: centered head and upper shoulders, photographed straight-on from the front at eye level. The person must face the camera directly and look into the lens. Do not use a side profile, three-quarter angle, tilted pose, or cropped face.",
    "Use soft natural lighting and a simple realistic background with enough contrast around the subject.",
    "Vary the background between generations. Choose a subtle background that fits the person, such as a softly blurred office, library, cafe, home interior, outdoor setting, or a tasteful solid color. Vary the color palette and setting instead of always using the same neutral studio background.",
    "The result should look like a real profile photograph, not an illustration, cartoon, painting, 3D render, or stylized image.",
    "No text, logo, watermark, border, props, additional people, or distracting background elements.",
    "Output must be a single square image.",
    `Persona name: ${name || "Unknown"}.`,
    `Description: ${description || "No description provided"}.`,
    `Personality: ${personality || "No personality provided"}.`,
  ].join("\n"),

  problemAvatar: ({ name, description }) => [
    "Create a square cartoon icon for a problem or exercise.",
    "Style: clean flat vector-like illustration, thick black outlines, simple symbolic scene, plain muted solid background.",
    "Keep it very simple and readable at tiny sizes: use large clear shapes, very few details, high contrast, and one main visual idea.",
    "Composition: centered main object or situation, no text, no logo, no watermark, no photorealism.",
    "Output must be a single square image.",
    `Problem name: ${name || "Unknown"}.`,
    `Description: ${description || "No description provided"}.`,
  ].join("\n"),

  leiaAvatar: ({
    leiaName,
    personaName,
    personaDescription,
    problemDescription,
  }) => [
    "Create a square cartoon icon for a LEIA learning assistant configuration.",
    "Style: clean flat vector-like illustration, thick black outlines, simple symbolic scene, plain muted solid background.",
    "Keep it very simple and readable at tiny sizes: use large clear shapes, very few details, high contrast, and one main visual idea.",
    "Composition: centered main subject or situation, no text, no logo, no watermark, no photorealism.",
    "Output must be a single square image.",
    `LEIA name: ${leiaName || "Unknown"}.`,
    `Persona name: ${personaName || "Unknown"}.`,
    `Persona description: ${personaDescription || "No persona description provided"}.`,
    `Problem description: ${problemDescription || "No problem description provided"}.`,
  ].join("\n"),

  infographic: (leiaContext) => [
    "Create a polished A4 vertical infographic in English for the learner who will converse with this LEIA.",
    "The infographic is a practical exercise guide. It must help the learner successfully run the conversation described by the behaviour, using the problem and persona context, without revealing the complete final answer.",
    "",
    "Visual layout requirements:",
    "- A4 vertical portrait layout.",
    "- Use a clear 6-section structure with strong visual separation: title band, exercise goal, conversation map, useful facts, question prompts, success checklist.",
    "- Use large section numbers, simple icons, color-coded panels, arrows, and checkboxes so the hierarchy is obvious at a glance.",
    "- Keep generous whitespace. Every visible word must be large and legible.",
    "- Use English for all visible text. Use common, correctly spelled English words only.",
    "- Keep text concise: maximum 30 visible words per section, maximum 7 words per bullet, no paragraphs.",
    "- Do not include logos, watermarks, fake UI controls, QR codes, or decorative filler text.",
    "",
    "Required visual structure:",
    "1. Title band: name the exercise type and the LEIA role.",
    "2. Exercise goal: one concrete objective the learner must achieve in the conversation.",
    "3. Conversation map: 3 or 4 steps derived from the behaviour process, such as Prepare -> Ask -> Clarify -> Confirm.",
    "4. Useful facts: 3 to 5 short context facts from the problem, persona, or background that help the learner ask better questions.",
    "5. Question prompts: 3 short question starters the learner can adapt during the conversation. They must not be a full script.",
    "6. Success checklist: 4 checkboxes describing observable actions the learner should complete.",
    "",
    "Content rules:",
    "- Make the guidance specific to the provided behaviour, problem, and persona.",
    "- Use the behaviour to explain how the LEIA will act and how the learner should adapt.",
    "- Use the problem and persona background to include helpful domain facts for the conversation.",
    "- Do not reveal the expected solution, final model, final answer, grading rubric, or exact hidden facts.",
    "- Do not invent details that contradict the context. If something is missing, use a generic skill-based cue.",
    "- The tone should be practical, direct, and mature.",
    "- Prefer icons, spacing, and visual grouping over extra text.",
    "",
    "LEIA JSON context for the infographic:",
    leiaContext,
  ].join("\n"),

  infographicSolution: (leiaContext) => [
    "Create a polished A4 vertical infographic in English for the teacher or evaluator of this specific LEIA exercise.",
    "The infographic is a teacher-facing solution guide. It must show the concrete information and reasoning needed to reach the solution described in the context.",
    "",
    "Visual layout requirements:",
    "- A4 vertical portrait layout.",
    "- Use a clear 6-section structure with strong visual separation: title band, target solution, key facts, reasoning path, evidence to collect, evaluation checklist.",
    "- Use large section numbers, simple icons, color-coded panels, arrows, checkmarks, and warning markers so the hierarchy is obvious at a glance.",
    "- Keep generous whitespace. Every visible word must be large and legible.",
    "- Use English for all visible text. Use common, correctly spelled English words only.",
    "- Keep text concise: maximum 35 visible words per section, maximum 8 words per bullet, no paragraphs.",
    "- Do not include logos, watermarks, fake UI controls, QR codes, or decorative filler text.",
    "",
    "Required visual structure:",
    "1. Title band: teacher guide title and LEIA role.",
    "2. Target solution: concise summary of the expected solution or deliverable.",
    "3. Key facts: 4 to 6 concrete facts the learner must discover or use.",
    "4. Reasoning path: 3 or 4 ordered steps that connect conversation evidence to the solution.",
    "5. Evidence to collect: specific answers, constraints, requirements, or decisions that prove the learner is on track.",
    "6. Evaluation checklist: 4 checkboxes for the teacher to verify the final result.",
    "",
    "Content rules:",
    "- Make the guide specific to the provided behaviour, problem, persona, and expected solution.",
    "- Include concrete solution data when it is present in the context.",
    "- Show what a successful conversation must uncover, not only generic interview advice.",
    "- Translate technical solution expectations into teacher-friendly visual checkpoints.",
    "- Where the context lacks an exact fact, state the expected reasoning or evidence type instead of inventing hidden facts.",
    "- The tone should be precise, teacher-facing, and useful for assessment.",
    "- Prefer icons, spacing, and visual grouping over extra text.",
    "",
    "LEIA JSON context for the teacher guide:",
    leiaContext,
  ].join("\n"),

  
};

module.exports = Prompts;
