const Prompts = {
  evaluation: (solution, result, solutionFormat, evaluationPrompt) => [
    'Evaluate the following solution for a problem:',
    '',
    'Expected solution:',
    solution,
    '',
    'Provided solution:',
    result,
    '',
    'The Format to compare is:',
    solutionFormat,
    '',
    'Evaluate the provided solution by comparing it with the expected solution.',
    'Assign a score between 0 and 10, where:',
    '- 10 means the solution is perfect',
    '- 0 means the solution is completely incorrect',
    'Provide a detailed evaluation in Markdown format.',
    '',
    'Respond ONLY with a JSON object in the following format:',
    '{',
    '  "score": [score between 0 and 10],',
    '  "evaluation": "[detailed evaluation in Markdown format]"',
    '}',
    ...(evaluationPrompt ? ['', evaluationPrompt] : []),
  ].join('\n'),

  personaAvatar: ({ name, description, personality }) => [
    "Create a realistic square profile photo of a person.",
    "Style: natural photorealistic headshot, professional but approachable, with realistic skin texture, facial features, hair, and clothing.",
    "Composition: centered head and upper shoulders, photographed straight-on from the front at eye level. The person must face the camera directly and look into the lens. Do not use a side profile, three-quarter angle, tilted pose, or cropped face.",
    "Use soft natural lighting and a simple realistic background with enough contrast around the subject.",
    "Vary the background between generations. Choose a subtle background that fits the person, such as a softly blurred office, library, cafe, home interior, outdoor setting, or a tasteful solid color. Vary the color palette and setting instead of always using the same neutral studio background.",
    "The result should look like a real profile photograph, not an illustration, cartoon, painting, 3D render, or stylized image.",
    "No text, logo, watermark, border, props, additional people, or distracting background elements.",
    "Output must be a single square image.",
    `Persona name: ${name || "Unknown"}.`,
    `Description: ${description || "No description provided"}.`,
    `Personality: ${personality || "No personality provided"}.`,
  ].join("\n"),

  problemAvatar: ({ name, description }) => [
    "Create a square cartoon icon for a problem or exercise.",
    "Style: clean flat vector-like illustration, thick black outlines, simple symbolic scene, plain muted solid background.",
    "Keep it very simple and readable at tiny sizes: use large clear shapes, very few details, high contrast, and one main visual idea.",
    "Composition: centered main object or situation, no text, no logo, no watermark, no photorealism.",
    "Output must be a single square image.",
    `Problem name: ${name || "Unknown"}.`,
    `Description: ${description || "No description provided"}.`,
  ].join("\n"),

  leiaAvatar: ({
    leiaName,
    personaName,
    personaDescription,
    problemDescription,
  }) => [
    "Create a square cartoon icon for a LEIA learning assistant configuration.",
    "Style: clean flat vector-like illustration, thick black outlines, simple symbolic scene, plain muted solid background.",
    "Keep it very simple and readable at tiny sizes: use large clear shapes, very few details, high contrast, and one main visual idea.",
    "Composition: centered main subject or situation, no text, no logo, no watermark, no photorealism.",
    "Output must be a single square image.",
    `LEIA name: ${leiaName || "Unknown"}.`,
    `Persona name: ${personaName || "Unknown"}.`,
    `Persona description: ${personaDescription || "No persona description provided"}.`,
    `Problem description: ${problemDescription || "No problem description provided"}.`,
  ].join("\n"),

  infographic: (leiaContext) => [
    "Create a single-page A4 vertical educational infographic for the person who will perform the LEIA exercise.",
    "Purpose: help the learner understand the scenario, prepare the interaction, ask better questions, and complete the exercise more effectively.",
    "Audience: student / exercise participant.",
    "Language: use English unless the LEIA context is clearly written in another language; if so, use that language.",
    "",
    "Important content rules:",
    "- Do not reveal, infer, or include the final solution.",
    "- Do not include answer keys, model answers, hidden evaluation criteria, or instructor-only notes.",
    "- Focus on process guidance: what to observe, how to interview, what information to gather, what to clarify, and how to organize findings.",
    "- Base every element on the LEIA context below. Do not invent domain facts that are not supported by the context.",
    "",
    "Required infographic structure:",
    "1. A clear title with the exercise name or scenario.",
    "2. A short context summary in plain language.",
    "3. The learner's objective, phrased as an actionable task.",
    "4. A compact profile of the person/role to interview, including motivations, constraints, and communication style, but without revealing hidden solution facts.",
    "5. A section called 'How to Approach the Interview' with practical guidance for starting, listening, and following up.",
    "6. A section called 'Key Questions' with the best open-ended questions the learner should ask during the exercise.",
    "7. A section called 'Work Hints' with non-spoiler hints about categories of information to capture.",
    "8. A final checklist the learner can use before submitting the exercise.",
    "",
    "Visual design requirements:",
    "- Make it a polished, readable infographic poster, not a generic illustration.",
    "- Use a clean professional education style with strong hierarchy, icons, section blocks, and concise text.",
    "- Group the content into 4 to 6 visual blocks, with short bullets that remain legible.",
    "- Use a balanced color palette with good contrast; avoid tiny dense text.",
    "- Do not embed portraits, profile photos, avatars, or realistic images of the persona/interviewed person.",
    "- No logos, watermarks, fake UI chrome, QR codes, or unrelated decorative elements.",
    "",
    "LEIA context:",
    leiaContext || "No context provided.",
  ].join("\n"),

  infographicSolution: (leiaContext) => [
    "Create a single-page A4 vertical instructor-only infographic solution guide for a LEIA exercise.",
    "Purpose: give the evaluator or teacher a compact instructor guide that explains how the interview should be conducted and what evidence should be observed.",
    "Audience: instructor / evaluator. This version must not include the final answer as such.",
    "Language: use English unless the LEIA context is clearly written in another language; if so, use that language.",
    "",
    "Required content:",
    "1. A clear title that identifies this as the solution guide.",
    "2. A short scenario summary.",
    "3. 'Clear Personality Traits': identify the interview persona's visible personality traits, priorities, motivations, frustrations, constraints, and likely communication style.",
    "4. 'Best Interview Questions': list the strongest questions the learner should ask, grouped by theme when useful.",
    "5. 'Expected Key Information': list the facts, requirements, or evidence the learner should discover during the interview.",
    "6. 'Scoring Criteria': include concise checks for completeness, correctness, and quality without writing the final answer.",
    "7. 'Common Errors': mention likely mistakes or omissions to watch for.",
    "",
    "Content rules:",
    "- Use only information supported by the LEIA context below.",
    "- If a detail is missing, mark it as 'Not specified' instead of inventing it.",
    "- Do not include the final solution, model answer, completed deliverable, or solution text as such.",
    "- Be concrete and useful for grading; avoid vague advice.",
    "- Keep text concise enough to be readable in an infographic.",
    "",
    "Visual design requirements:",
    "- Make it a polished, readable solution guide infographic poster.",
    "- Use a professional instructor-facing style with clear hierarchy, icons, section blocks, and concise text.",
    "- Add a subtle visual label such as 'Instructor Only' or 'Solution Guide'.",
    "- Use good contrast and avoid tiny dense text.",
    "- Do not embed portraits, profile photos, avatars, or realistic images of the persona/interviewed person.",
    "- No logos, watermarks, fake UI chrome, QR codes, or unrelated decorative elements.",
    "",
    "LEIA context:",
    leiaContext || "No context provided.",
  ].join("\n"),

  
};

module.exports = Prompts;
