openapi: "3.1.0"

info:
  title: LEIA CUSTOMER API
  description: API for interacting with LEIA instances.
  version: "1.0.0"

servers:
  - url: /
    description: Local server
  - url: https://customer-leia-c532b43c578c.herokuapp.com
    description: Production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/v1/leias:
    post:
      operationId: createLeia
      summary: Creates a new LEIA instance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: string
                  description: Unique session ID
                leia:
                  type: object
                  description: LEIA configuration object
                runnerConfiguration:
                  type: object
                  properties:
                    provider:
                      type: string
                      description: Name of the model provider to use
      responses:
        "201":
          description: LEIA created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                  modelName:
                    type: string
                  created:
                    type: boolean
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "409":
          description: Session already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  sessionId:
                    type: string
                  modelName:
                    type: string
                  created:
                    type: boolean
                    default: false
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      security:
        - bearerAuth: []
  
  /api/v1/leias/{sessionId}/messages:
    post:
      operationId: sendLeiaMessage
      summary: Sends a message to a LEIA instance
      parameters:
        - name: sessionId
          in: path
          required: true
          description: Unique session ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: Message to send to LEIA
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "404":
          description: Session not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      security:
        - bearerAuth: []
        
  /api/v1/models:
    get:
      operationId: listModels
      summary: Lists available models
      responses:
        "200":
          description: List of available models
          content:
            application/json:
              schema:
                type: object
                properties:
                  models:
                    type: array
                    items:
                      type: string
                  default:
                    type: string
                    description: Configured default model
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      security:
        - bearerAuth: []
