name: "Keep Alive Upstash Redis Database"
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: PING VIA REST API
        env:
          REDIS_TOKEN: ${{ secrets.REDIS_UPSTASH_REST_TOKEN }}
          REDIS_URL: ${{ secrets.REDIS_UPSTASH_REST_URL }}
        run: |
          curl -sS -H "Authorization: Bearer $REDIS_TOKEN" "$REDIS_URL/ping"
